# Generated by Django 5.0.4 on 2026-04-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_label',
            field=models.CharField(help_text='Enter the label as printed on the physical asset', max_length=50, unique=True),
        ),
    ]
