# Generated by Django 5.0.4 on 2026-04-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0002_alter_asset_asset_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcheckout',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for notifications', max_length=254),
        ),
    ]
