# Generated by Django 5.0.4 on 2026-04-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0002_alter_asset_asset_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='kenyan_id',
            field=models.CharField(blank=True, help_text='Kenyan ID number', max_length=20),
        ),
    ]
