# Generated by Django 5.0.4 on 2026-04-17 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0003_staffprofile_kenyan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcheckout',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_checkouts', to='assets_app.department'),
        ),
        migrations.AddField(
            model_name='assetcheckout',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
