# Generated by Django 5.0.4 on 2026-04-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0005_assettype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='details',
        ),
        migrations.AddField(
            model_name='asset',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Total number of units initially received'),
        ),
        migrations.AddField(
            model_name='assetcheckout',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='assetcheckout',
            name='recipient_kenyan_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='assetcheckout',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='broken_items',
            field=models.TextField(blank=True, help_text='List broken or damaged items being reported'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='issue_details',
            field=models.TextField(blank=True, help_text='More details about the problem or damage'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='reported_by',
            field=models.CharField(blank=True, help_text='Name of the person reporting this issue', max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='acquired_by_name',
            field=models.CharField(help_text='Full name of person who received this asset into the hub', max_length=200),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('hr', 'HR'), ('dept_head', 'Department Head'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
