# Generated by Django 5.0.4 on 2026-04-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0006_remove_maintenancerecord_details_asset_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='current_holder',
            field=models.CharField(blank=True, help_text='Name of the person currently holding this asset', max_length=200),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='action_needed',
            field=models.TextField(blank=True, help_text='Actions required to fix the items'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='items_to_fix',
            field=models.TextField(blank=True, help_text='Items that need to be fixed'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approved by superadmin or HR'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('hr', 'HR'), ('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
