# Generated by Django 5.0.4 on 2026-04-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0003_assetcheckout_email'),
        ('assets_app', '0007_asset_current_holder_maintenancerecord_action_needed_and_more'),
    ]

    operations = [
    ]
