# Generated by Django 5.0.4 on 2026-04-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0008_merge_20260422_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('equipment', 'Equipment'), ('vehicles', 'Vehicles'), ('stationery', 'Stationery & Supplies'), ('facility', 'Facility'), ('software', 'Software & Licenses'), ('audiovisual', 'Audio/Visual'), ('networking', 'Networking'), ('office_equipment', 'Office Equipment'), ('security', 'Security'), ('appliances', 'Appliances'), ('books_media', 'Books & Media'), ('other', 'Other')], max_length=20),
        ),
    ]
