# Generated by Django 5.0.4 on 2026-04-22 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0009_alter_asset_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets_app.department'),
        ),
    ]
